// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGSz-Q74mfrraVNsCXg0giUQVwTrwgLj8',
    appId: '1:320231889114:web:6cf5620095690da8c26de3',
    messagingSenderId: '320231889114',
    projectId: 'hostinaar',
    authDomain: 'hostinaar.firebaseapp.com',
    storageBucket: 'hostinaar.appspot.com',
    measurementId: 'G-WGY1BEN1V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJGAplyauPfnDPr3t6bnbPLrYouNaQ00',
    appId: '1:320231889114:android:08f858b8e98b4461c26de3',
    messagingSenderId: '320231889114',
    projectId: 'hostinaar',
    storageBucket: 'hostinaar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP782M_gbxq71k0EJkjgwn9ZsDzPjC0ao',
    appId: '1:320231889114:ios:9e680a2e249fa651c26de3',
    messagingSenderId: '320231889114',
    projectId: 'hostinaar',
    storageBucket: 'hostinaar.appspot.com',
    iosBundleId: 'com.example.polygoniar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP782M_gbxq71k0EJkjgwn9ZsDzPjC0ao',
    appId: '1:320231889114:ios:39d55a1095ec55a3c26de3',
    messagingSenderId: '320231889114',
    projectId: 'hostinaar',
    storageBucket: 'hostinaar.appspot.com',
    iosBundleId: 'com.example.polygoniar.RunnerTests',
  );
}
